---
apiVersion: backstage.io/v1alpha1
kind: Resource
metadata:
  name: d6fb0a12-5578-4671-a2dc-52892dd058c2
  namespace: terrazzo-local
spec:
  implementation:
    apiVersion: buildkite.elastic.dev/v1
    kind: Pipeline
    metadata:
      description: Enterprise Search PHP Client
      name: enterprise-search-php
    spec:
      default_branch: null
      repository: elastic/enterprise-search-php
      teams:
        devtools-team: {}
        everyone:
          access_level: READ_ONLY
  owner: group:devtools-team
  type: buildkite-pipeline
