#!/usr/bin/env bash
#
# Version 1.1
# - Moved to .ci folder and seperated out `run-repository.sh`
# - Add `$RUNSCRIPTS` env var for running Elasticsearch dependent products
export CONTAINER_NAME=enterprise-search

script_path=$(dirname $(realpath -s $0))
source $script_path/functions/imports.sh
set -euo pipefail

echo "--- :docker: :elasticsearch: Starting Elasticsearch"
DETACH=true bash $script_path/run-elasticsearch.sh

echo "--- :docker: :elastic-enterprise-search: Starting Enterprise Search"
DETACH=true bash $script_path/run-enterprise-search.sh

echo "+++ :php: Run Client Tests"
bash $script_path/run-repository.sh
